### ISSUE TITLE
Error running acclingo

### ISSUE THREAD

**Issue by javier-romero** [mlindauer/ac_clingo#10]
Hi, 

I get an error trying to run acclingo, could you please help me with it?

```
$ python scripts/acclingo --instance-dir ./examples --binary binaries/clingo
Traceback (most recent call last):
  File "scripts/acclingo", line 12, in <module>
    from acclingo.acclingo import ACClingo
  File "/home/davila/git/potassco/acclingo/acclingo/acclingo.py", line 10, in <module>
    from acclingo.tae.clasp_tae import ClaspTAE
  File "/home/davila/git/potassco/acclingo/acclingo/tae/clasp_tae.py", line 7, in <module>
    from smac.tae.execute_ta_run import StatusType, ExecuteTARun
ModuleNotFoundError: No module named 'smac.tae.execute_ta_run'
$ python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smac.tae
>>> import smac.tae.execute_ta_run
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'smac.tae.execute_ta_run'
>>> print(smac.__version__)
0.13.1
```

**Comment by mlindauer** [comment]
Hi, 

Sorry, acclingo is only compatible with SMAC 0.12. We changed the SMAC classes for calling target algorithms. Please downgrade SMAC.

**Comment by javier-romero** [comment]
Thank you Marius!
